{
	int a = 0;
	int b = 1;
	int c = 0;
	int d = 4;
	int e = 2;
	int f = 3;
	int r = 4;
	int u = 7;
	
	int m = a + b;
	int n = a + b;
	if (1)
	{
		int p = c + d;
		r = c + d;
	}
	else
	{
		int q = a + b;
		r = c + d;
		if (1)
		{
			e = b + 5;
			int s = a + b;
			u = e + f;
		}
		else
		{
			e = b + 8;
			int t = c + d;
			u = e + f;
		}
		int v = a + b;
		int w = c + d;
		int x = e + f;
	}
	int y = a + b;
	int z = c + d;
}